function geomWritePlyAscii(filename, V, F)
% V: [Nv x 3], F: [Nf x 3] 1-based indices
fid = fopen(filename, "w");
assert(fid>0, "Cannot open PLY file for writing: %s", filename);

Nv = size(V,1);
Nf = size(F,1);

% PLY header
fprintf(fid, "ply\n");
fprintf(fid, "format ascii 1.0\n");
fprintf(fid, "comment generated by datasetScene\n");
fprintf(fid, "element vertex %d\n", Nv);
fprintf(fid, "property float x\n");
fprintf(fid, "property float y\n");
fprintf(fid, "property float z\n");
fprintf(fid, "element face %d\n", Nf);
fprintf(fid, "property list uchar int vertex_indices\n");
fprintf(fid, "end_header\n");

% vertices
fprintf(fid, "%.9g %.9g %.9g\n", V.');

% faces (PLY uses 0-based indices)
F0 = F - 1;
fprintf(fid, "3 %d %d %d\n", F0.');

fclose(fid);
end